version: Wesnoth-VS2013-{branch}-{build}
clone_folder: C:\projects\wesnoth
image: Visual Studio 2013
configuration:
 - Release
 - Debug
platform: win32
skip_branch_with_pr: true
shallow_clone: true
before_build:
  - cd ..
  - ps: wget https://github.com/aquileia/external/archive/VC12.zip -O VC12.zip
  - 7z x VC12.ZIP
  - ren external-VC12 external
  - cd wesnoth
  - set PATH=C:\projects\external\dll;%PATH%

on_success:
  - python utils\appveyor\irc-notify.py wesnoth-appveyor-status [{project_name}:{branch}] {short_commit}: \"{message}\" ({author}) {color_green}Succeeded,Details: {build_url},Commit: {commit_url}"

on_failure:
  - python utils\appveyor\irc-notify.py wesnoth-appveyor-status [{project_name}:{branch}] {short_commit}: \"{message}\" ({author}) {color_red}Failed,Details: {build_url},Commit: {commit_url}"