language: cpp
compiler:
    - clang
    - gcc
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq unixodbc-dev libboost1.48-all-dev libboost-iostreams1.48-dev libboost-program-options1.48-dev libboost-regex1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-date-time1.48-dev libcairo2-dev libfribidi-dev libpango1.0-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
    - sudo apt-get auto libboost1.46-all-dev
    - dpkg -S /usr/include/boost/signals2/detail/auto_buffer.hpp
script: scons cxxtool=$CXX wesnoth wesnothd umcd
notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#wesnoth-dev"
        template:
            - "\x02%{repository}\x0f#\x0312%{build_number}\x0f (\x0307%{branch}\x0f - \x02%{commit}\x0f : \x0303%{author}\x0f): \x02%{message}\x0f"
            - "Build details : \x0302%{build_url}\x0f"
        on_success: change
        on_failure: always
