language: cpp
compiler:
    - clang
    - gcc
env:
    - WML_TESTS=true STRICT_COMPILATION=True
    - WML_TESTS=true STRICT_COMPILATION=False
    - WML_TESTS=false STRICT_COMPILATION=True
matrix:
  exclude:
    - compiler: clang 
      env: WML_TESTS=false STRICT_COMPILATION=True
    - compiler: gcc 
      env: WML_TESTS=true STRICT_COMPILATION=True
    - compiler: gcc
      env: WML_TESTS=true STRICT_COMPILATION=False
before_install:
    - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-iostreams-dev libboost-program-options-dev libboost-regex-dev libboost-system-dev libboost-test-dev libcairo2-dev libfribidi-dev libpango1.0-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
script: 
    - scons cxxtool=$CXX strict=$STRICT_COMPILATION wesnoth wesnothd campaignd test
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - ./test_wrapper.sh
    - if [[ "$WML_TESTS" = true ]]; then ./run_wml_tests -t 20; fi
after_failure:
    - ./travis_after_failure.sh
notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#wesnoth-dev"
        template:
            - "\x02%{repository}\x0f#\x0312%{build_number}\x0f (\x0307%{branch}\x0f - \x02%{commit}\x0f : \x0303%{author}\x0f): \x02%{message}\x0f"
            - "Build details : \x0302%{build_url}\x0f"
        on_success: change
        on_failure: always
