language: cpp
compiler:
    - clang
    - gcc
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-iostreams-dev libboost-program-options-dev libboost-regex-dev libboost-system-dev libboost-thread-dev libcairo2-dev libfribidi-dev libpango1.0-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
script: scons cxxtool=$CXX
branches:
    only:
        - master
        - 1.10
notifications:
    email: false
    irc:
        - "chat.freenode.net#wesnoth-test"
